config/routes.rb
Bauer::Application.routes.draw do

  get 'about', :to => 'pages#about', :as => 'about'
  get 'projects', :to => 'pages#projects', :as => 'projects'
  get 'contact', :to =>'pages#contact', :as => 'contact'
  root :to => 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shane Bauer - ShaneBauer.com - Software Development Portfolio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
	<!--[if lt IE 9]>
    	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container wrap">
		<div class="content">
			<header class="row upper">
				<div class="col-md-7">
					<h1>Shane Bauer</h1>
					<p>Experienced Software Developer, ASP.NET, C#, Ruby, Rails</p>
				</div>
				<div class="col-md-5">
					<nav>
						<ul class="nav nav-pills">

					    	<%=nav_link 'Home',root_path%>
							<%=nav_link 'About Me',about_path%>
							<%=nav_link 'Projects',projects_path%>
					  		<%=nav_link 'Contact',contact_path%>
						</ul>
					</nav>
				</div>
			</header>
			<div class="row" style="margin-top: 10px">
				<div class="col-md-9">
					<%=yield %>
				</div>
				<div class="col-md-3">
					<h3>Let's Connect</h3>
					 <%=render :partial=>'shared/connections' %>
				</div>
			</div>
			
			<footer class="row" >
				<div class="col-md-12">
					&copy;2002-2014. Shane Bauer
				</div>
			</div>
		</div>
		<!-- Start of StatCounter Code for Default Guide -->
		<script type="text/javascript">
		var sc_project=7884659; 
		var sc_invisible=1; 
		var sc_security="2f10cc15"; 
		</script>
		<script type="text/javascript"
		src="http://www.statcounter.com/counter/counter.js"></script>
		<noscript><div class="statcounter"><a title="tumblr
		analytics" href="http://statcounter.com/tumblr/"
		target="_blank"><img class="statcounter"
		src="http://c.statcounter.com/7884659/0/2f10cc15/1/"
		alt="tumblr analytics"></a></div></noscript>
		<!-- End of StatCounter Code for Default Guide -->
	</body>
</html>

app/views/pages/about.html.erb
<h3>About Me</h3>
<p>When I was in high school, I realized that I loved programming. I spent most of my summer vacations writing code for various websites. After high school I decided to make a career out of it. I have been developing software professionally for almost 12 years and still enjoy it. I currently write web applications using Ruby on Rails and ASP.NET MVC for both small and large companies.</p>

<p>I am a husband and father of my <a href="http://www.baltimoresun.com/news/maryland/bs-md-momo-twins-20120324,0,7096332.story" target="_blank">twin</a> <a href="http://www.baltimoresun.com/health/bs-md-momo-twins-first-trip-20120419,0,1093541.story" target="_blank">boys</a> <a href="http://perryhall.patch.com/articles/rare-momo-babies-born-to-perry-hall-parents" target="_blank">that</a> were born in February of 2012.</p> 

<h3>Technologies</h3>
<p>ASP (VBScript), ASP.NET 1.0/1.1/2.0/3.5 (C#/VB.NET), Perl, PHP, SQL, TSQL, HTML, JavaScript, Ruby</p>

<p>Git, Mercurial, Subversion, MbUnit, NUnit, TeamCity, CruiseControl .NET, ASP.NET AJAX, AJAX Control Toolkit, Nant, MSBuild, ReSharper 2.x/3.x, iTextSharp, MonoRail, ASP.NET MVC, Ruby on Rails 1.x/2.x/3.x</p>

<p>Windows 9x,2000,XP,2003, Mac OSX, AIX, Linux</p>

<p>IIS 5.0/5.1/6.0, Apache 1.x/2.0, Microsoft SQL Server 2000/2005, MySQL, PostgreSQL, Visual Studio 6/2002/2003/2005/2008/2010, ADSI, COM, WMI, Microsoft SMS Server, SQL Server Reporting Services</p>

<p>Interested in: Domain-Driven Design, Test-Driven Development, Application Design</p>

app/views/pages/contact.html.erb
<h3>Contact Me</h3>
<p>I'm available via email, and Skype. You can also contact me via one of the social media links on the right side. </p>
<p><strong>Email:</strong> shane [at] shanebauer.com</p>
<p><strong>Skype:</strong> sbauer318</p>

app/views/pages/index.html.erb
<h3>Little Bit About Me</h3>
<p>I'm an experienced software developer based out of Baltimore, Maryland. I spend most of my time working on web-based software applications. I have developed applications for small and large businesses. I also work on projects just for fun. Most of my projects have been written in Ruby/Ruby on Rails and C#/ASP.NET MVC.</p>
<br/>
<h3>About the Site</h3>
<p>This site was created using Ruby on Rails 4, and Twitter Bootstrap (I'm an awful designer). The site is currently hosted by Heroku. </p>

app/views/pages/projects.html.erb
<h3>Projects</h3>
<p>I'm currently working on a few projects. I'll update this page when they're ready.</p>

app/views/shared/_connections.html.erb
<p><a href="http://www.linkedin.com/in/sbauer318">

          <img src="http://www.linkedin.com/img/webpromo/btn_myprofile_160x33.png" width="160" height="33" border="0" alt="View Shane Bauer's profile on LinkedIn">

    </a></p>
	<p><a href="https://twitter.com/sbauer318" class="twitter-follow-button" data-show-count="false">Follow @sbauer318</a>
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>
<p><a href="http://github.com/sbauer">My GitHub Profile</a></p>